# Generated by Django 3.1.5 on 2021-01-31 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name and Surname')),
                ('slug', models.SlugField(unique=True)),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Age')),
                ('birthday', models.DateField(default=datetime.datetime(2021, 1, 31, 22, 3, 43, 746519, tzinfo=utc), verbose_name='Birthday')),
                ('description', models.TextField(max_length=250)),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Main photo of the actor')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('public_date', models.DateTimeField(default=datetime.datetime(2021, 1, 31, 22, 3, 43, 747519, tzinfo=utc), verbose_name='Date published')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Pictures')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Budget')),
                ('fees', models.PositiveIntegerField(default=0, verbose_name='Fees')),
                ('actors', models.ManyToManyField(to='content.Actor', verbose_name='actors')),
                ('genres', models.ManyToManyField(to='content.Genre', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='ReviewForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('name_ip_user', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.reviewforum')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'review-forum',
            },
        ),
        migrations.CreateModel(
            name='FootageMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Footage from film')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.movie')),
            ],
        ),
        migrations.CreateModel(
            name='FootageActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actor_shots/', verbose_name='Photos of the actor')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.actor')),
            ],
        ),
    ]
